### ISSUE TITLE
@0x/sol-profiler not working with solc 0.7.6

### ISSUE THREAD

**Issue by lcswillems** [0xProject/tools#34]
## Expected Behavior

`@0x/sol-profiler` works with solc 0.7.5 with solc but not with 0.7.6.

Here is a reproduction: https://github.com/lcswillems/0x-profiler-error-0.7.6

I get this error:

```
TypeError: Cannot read property 'split' of undefined
    at Object.parseSourceMap (/mnt/Data/Downloads/dev-tools-truffle-example/node_modules/@0x/sol-tracing-utils/src/source_maps.ts:53:28)
    at TraceCollector.<anonymous> (/mnt/Data/Downloads/dev-tools-truffle-example/node_modules/@0x/sol-tracing-utils/src/trace_collector.ts:106:33)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/Data/Downloads/dev-tools-truffle-example/node_modules/@0x/sol-tracing-utils/lib/src/trace_collector.js:5:58)
```

After investigation, it seems the profiler assumes contract artifact contains a field `compilerOutput.evm.deployedBytecode.sourceMap` which is not the case.

**Comment by lcswillems** [comment]
I don't think it should be closed.

**Comment by lcswillems** [comment]
I don't think it should be closed.

**Comment by lcswillems** [comment]
I don't think it should be closed.
